name: Publish Docker image
on:
  push:
    branches:
      - test
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        run: |
          TAG="ghcr.io/${{ github.actor }}/${{ github.repository }}:$(date -u '+%Y%m%d%H%M%S')"
          docker build -t minid:latest -f Dockerfile.minid .
          cat Dockerfile \
            | docker run -i --rm minid:latest minid -f - \
            | docker build --build-arg APT_MIRROR=US --tag "${TAG}" -f - .
          docker login -u "${{ github.actor }}" -p "${{ secrets.CONTAINER_REGISTRY_TOKEN }}" ghcr.io
          docker push "${TAG}"
